### PR TITLE
Implemented noise effects in OpenGL.

### PR DESCRIPTION
**Pull request by MaikelChan**
Noise effects implemented in OpenGL (vanish cap, teleportation, and Bowser vanish after defeat).

### CODE REVIEW

**Comment by coltongit** [comment]
This looks good to me. Has it been extensively tested by any chance?

**Comment by MaikelChan** [comment]
I've done more testing on D3D11 than OpenGL, but the implementation is the same. I'm doing a 120 star playthrough and I haven't seen anything unexpected.

**Comment by coltongit** [comment]
Sounds like it's working well so far then.

**Comment by coltongit** [comment]
@Emill do you think this is ready to merge?

**Comment by Emill** [comment]
Works fine but I admit it looks a bit strange for large resolutions.

**Pull request merged**
